name: CI

on: workflow_dispatch

jobs:
  pytest:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: actions/checkout@v2
    - name: Install Poetry
      run: pip install poetry
    - name: Install Dependencies
      run: poetry install
    - name: Test with pytest  
      run: |  
        poetry run pytest tests -v -s